/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.isetj.guicassandra.gui;

import static com.codahale.metrics.SharedMetricRegistries.clear;
import static com.datastax.driver.core.querybuilder.QueryBuilder.delete;
import com.isetj.guicassandra.dao.CassandraConnector;
import com.isetj.guicassandra.jpa.CityEntity;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.City;
import model.Covid19;
import swingcrud.jpa.RegionEntity;
import swingcrud.model.Region;
 
/**
 *
 * @author MSellami
 */
public class CovidGUI extends javax.swing.JFrame {

    /**
     * Creates new form CityGUI
     */
    
    public CovidGUI() {

        initComponents();

    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPConnection = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbConnect = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jtxtNode = new javax.swing.JTextField();
        jtxtPort = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtNode2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jbInitDB = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtxtDbName = new javax.swing.JTextField();
        jPCity = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtCityID = new javax.swing.JTextField();
        jtxtLongitude = new javax.swing.JTextField();
        jtxtLatitude = new javax.swing.JTextField();
        jSpPopulation = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbCities = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbAdd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jbRefresh = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jtxtCityName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtPop = new javax.swing.JSpinner();
        txtLid = new javax.swing.JSpinner();
        txtConfirmes = new javax.swing.JSpinner();
        txtMorts = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLongitude = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLatitude = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtFname = new javax.swing.JTextPane();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Cassandra Cluster Node");

        jLabel6.setText("Port");

        jbConnect.setText("Connect");
        jbConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConnectActionPerformed(evt);
            }
        });

        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jtxtNode.setText("127.0.0.1");

        jtxtPort.setText("9042");

        jLabel7.setText("User");

        jtxtNode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNode2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Password");

        jPasswordField1.setText("jPasswordField1");

        jbInitDB.setText("Init Database");
        jbInitDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInitDBActionPerformed(evt);
            }
        });

        jLabel9.setText("Database");

        jtxtDbName.setText("Covid19DB");
        jtxtDbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDbNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jbConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtDbName, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbInitDB, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNode2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtxtNode, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addComponent(jtxtPort)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtDbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtNode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConnect)
                    .addComponent(jButton6)
                    .addComponent(jbInitDB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPConnectionLayout = new javax.swing.GroupLayout(jPConnection);
        jPConnection.setLayout(jPConnectionLayout);
        jPConnectionLayout.setHorizontalGroup(
            jPConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConnectionLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPConnectionLayout.setVerticalGroup(
            jPConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConnectionLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(380, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Connection", jPConnection);

        jPCity.setBorder(javax.swing.BorderFactory.createTitledBorder("City Infos:"));

        jLabel1.setText("City Name:");

        jLabel2.setText("Longitude");

        jLabel3.setText("Latitude");

        jLabel4.setText("Population");

        jtxtCityID.setText("1");
        jtxtCityID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCityIDActionPerformed(evt);
            }
        });

        jtxtLongitude.setText("35.254879");

        jtxtLatitude.setText("35.254879");

        jSpPopulation.setModel(new javax.swing.SpinnerNumberModel(450.0d, null, null, 1.0d));

        jTbCities.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTbCities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "City ID", "City Name", "Longitude", "Latitude", "Population"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTbCities.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jTbCitiesAncestorRemoved(evt);
            }
        });
        jTbCities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbCitiesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTbCities);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Operations"));

        jbAdd.setText("Add");
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jbRefresh.setText("Refresh");
        jbRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jbAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbAdd)
                .addGap(18, 18, 18)
                .addComponent(jbRefresh)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jLabel10.setText("City ID");

        jtxtCityName.setText("Jendouba");
        jtxtCityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCityNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCityLayout = new javax.swing.GroupLayout(jPCity);
        jPCity.setLayout(jPCityLayout);
        jPCityLayout.setHorizontalGroup(
            jPCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCityLayout.createSequentialGroup()
                .addGroup(jPCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCityLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPCityLayout.createSequentialGroup()
                        .addGroup(jPCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCityLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(317, 317, 317))
                            .addGroup(jPCityLayout.createSequentialGroup()
                                .addGroup(jPCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPCityLayout.createSequentialGroup()
                                        .addGroup(jPCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPCityLayout.createSequentialGroup()
                                                .addGroup(jPCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel3))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPCityLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(73, 73, 73)))
                                .addGroup(jPCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPCityLayout.createSequentialGroup()
                                        .addComponent(jSpPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPCityLayout.createSequentialGroup()
                                        .addGroup(jPCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtLatitude, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                            .addComponent(jtxtCityName)
                                            .addComponent(jtxtCityID)
                                            .addComponent(jtxtLongitude))
                                        .addGap(207, 207, 207)))))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPCityLayout.setVerticalGroup(
            jPCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCityLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCityLayout.createSequentialGroup()
                        .addGroup(jPCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtCityID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jtxtCityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jSpPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        jTabbedPane1.addTab("Cities", jPCity);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("COVID-19");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("City Infos:");

        jLabel13.setText("City ID");

        jLabel14.setText("City name");

        jLabel15.setText("Longitude");

        jLabel16.setText("Latitude");

        jLabel18.setText("Population");

        jLabel19.setText("Nbr cas confirmés");

        jLabel20.setText("Nbr cas morts");

        jScrollPane2.setViewportView(txtLongitude);

        jScrollPane3.setViewportView(txtLatitude);

        jScrollPane4.setViewportView(txtFname);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Operations:");

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton5.setText("courbe");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "City ID", "City Name", "Longitude", "Latitude", "Population", "Confirmes", "Morts"
            }
        ));
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblStudents);
        tblStudents.getAccessibleContext().setAccessibleParent(txtLongitude);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLabel11)
                            .addGap(39, 39, 39))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel18)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(55, 55, 55)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMorts)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(txtPop)
                    .addComponent(txtConfirmes)
                    .addComponent(txtLid, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(190, 190, 190))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtLid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(delete))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtConfirmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMorts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Covid-19", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Statistiques", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(689, 689, 689))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCityIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCityIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCityIDActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jtxtNode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNode2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNode2ActionPerformed

    private void jbConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConnectActionPerformed
        // TODO add your handling code here:
        try {
            CassandraConnector.connect(jtxtNode.getText(), Integer.parseInt(jtxtPort.getText()), "", "");
            JOptionPane.showMessageDialog(this, "Connection with Success", "Connection", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error Connection", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jbConnectActionPerformed

    private void jbInitDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInitDBActionPerformed
        try {
            CassandraConnector.createKeyspace(jtxtDbName.getText(), "SimpleStrategy", 1);
            JOptionPane.showMessageDialog(this, "Database Initialization with Success", "Connection", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(this, e.getMessage(), "Database Initialization Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jbInitDBActionPerformed

    private void jtxtDbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDbNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDbNameActionPerformed

    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed
        // TODO add your handling code here:
        City city = new City(Integer.parseInt(jtxtCityID.getText()), this.jtxtCityName.getText(), Double.parseDouble(this.jtxtLongitude.getText()), Double.parseDouble(this.jtxtLatitude.getText()), Double.parseDouble(this.jSpPopulation.getValue().toString()));
        try {
            //insertion d'une nouvelle ville
            CityEntity.insertCity(city, this.jtxtDbName.getText());
            //recuperer tous les cities inseres dans la bases
            List<City> Cities = CityEntity.selectAll(this.jtxtDbName.getText());
            //Creer un model pour la table/schema
            DefaultTableModel model = new DefaultTableModel(new Object[]{"ID City", "City Name", "Longitude", "Latitude", "Population"}, 0);
            for (City City : Cities) {
                model.addRow(new Object[]{City.getIDCity(), City.getCityName(), City.Longitude, City.Latitude, City.getPopulation()});
            }
            jTbCities.setModel(model);
            JOptionPane.showMessageDialog(this, "Adding City with Success", "Connection", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(this, e.getMessage(), "Database Insert Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jbAddActionPerformed

    private void jtxtCityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCityNameActionPerformed

    private void jbRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshActionPerformed

 try {
            
            List<City> Cities = CityEntity.selectAll(this.jtxtDbName.getText());
            DefaultTableModel model = new DefaultTableModel(new Object[]{"ID City", "City Name", "Longitude", "Latitude", "Population"}, 0);
            for (City City : Cities) {
                model.addRow(new Object[]{City.getIDCity(), City.getCityName(), City.Longitude, City.Latitude, City.getPopulation()});
            }
            jTbCities.setModel(model);
            JOptionPane.showMessageDialog(this, "Refresh City with Success", "Connection", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(this, e.getMessage(), "Database Refresh Error", JOptionPane.ERROR_MESSAGE);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jbRefreshActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int i =jTbCities.getSelectedRow();
        DefaultTableModel tblmodel = (DefaultTableModel) jTbCities.getModel();
        if(i>=0)
        {
            tblmodel.setValueAt(jtxtCityID.getText(), i, 0);
            tblmodel.setValueAt(jtxtCityName.getText(), i, 1);
            tblmodel.setValueAt(jtxtDbName.getText(), i, 2);
            tblmodel.setValueAt(jtxtLatitude.getText(), i, 3);
            tblmodel.setValueAt(jtxtLongitude.getText(), i, 4);
            
        }else{
            JOptionPane.showMessageDialog(null, "error");
        }
        
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           // TODO add your handling code here:
           DefaultTableModel tblmodel = (DefaultTableModel) jTbCities.getModel();
           if(jTbCities.getSelectedRowCount()==1){
              tblmodel.removeRow(jTbCities.getSelectedRow()); 
           }
           else{
               if(jTbCities.getRowCount()==0){
                   JOptionPane.showMessageDialog(this,"table is empty");
               }
               else{
                   JOptionPane.showMessageDialog(this,"please select any single row for delete");
               }
           }
           
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTbCitiesAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTbCitiesAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTbCitiesAncestorRemoved

    private void jTbCitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbCitiesMouseClicked
        // TODO add your handling code here:
        int SelectedRow = jTbCities.getSelectedRow();
         DefaultTableModel tblmodel = (DefaultTableModel) jTbCities.getModel();
        jtxtCityID.setText(tblmodel.getValueAt(SelectedRow,0).toString());
        jtxtCityName.setText(tblmodel.getValueAt(SelectedRow,1).toString());
        jtxtDbName.setText(tblmodel.getValueAt(SelectedRow,2).toString());
        jtxtLatitude.setText(tblmodel.getValueAt(SelectedRow,3).toString());
        jtxtLongitude.setText(tblmodel.getValueAt(SelectedRow,4).toString());
        
        
    }//GEN-LAST:event_jTbCitiesMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
             if(jtxtCityID.getText().equals("")|| txtFname.getText().equals("")||txtLongitude.getText().equals("")||txtLatitude.getText().equals("")||jtxtCityID.getText().equals("")||jtxtCityID.getText().equals("")||jtxtNode2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter all data");}
        else{

            String data [] ={ jtxtCityID.getText(),txtFname.getText(),txtLongitude.getText(),txtLatitude.getText(),jtxtCityID.getText(),jtxtCityID.getText(),jtxtCityID.getText()};
            DefaultTableModel tblmode = (DefaultTableModel)tblStudents.getModel();
            tblmode.addRow(data);
            JOptionPane.showMessageDialog(this, "add data succsussfly");

          

        }   
             
        
     

          
       

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
          DefaultTableModel tblmodel = (DefaultTableModel) tblStudents.getModel();
           if(tblStudents.getSelectedRowCount()==1){
              tblmodel.removeRow(tblStudents.getSelectedRow()); 
           }
           else{
               if(tblStudents.getRowCount()==0){
                   JOptionPane.showMessageDialog(this,"table is empty");
               }
               else{
                   JOptionPane.showMessageDialog(this,"please select any single row for delete");
               }
           }
           
    }//GEN-LAST:event_deleteActionPerformed
private void btSaveNoSQL(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        String fname = txtFname.getText().trim();
        int lid = (int) txtLid.getValue();
        String longitude = txtLongitude.getText().trim();
        String latitude = txtLatitude.getText().trim();
        int pop = (int) txtPop.getValue();
        int confirmes = (int) txtConfirmes.getValue();
        int morts = (int) txtMorts.getValue();

        System.out.println(pop);
        if (!fname.isEmpty() && !longitude.isEmpty() && !latitude.isEmpty()) {
             
             
                com.datastax.driver.core.ResultSet rs = swingcrud.jpa.nosql.RegionEntityNoSQL.selectRegionbyID(lid);
                //si resultat est null
                if (!rs.wasApplied()) {
                    swingcrud.jpa.nosql.RegionEntityNoSQL.saveRegion(lid, fname, longitude, latitude, pop, confirmes, morts);
                   
                } else {
                    JOptionPane.showConfirmDialog(this,"Please provide a different id number","Save with success", JOptionPane.INFORMATION_MESSAGE);
                }
                 rs = swingcrud.jpa.nosql.RegionEntityNoSQL.selectAllRegion();
                  DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
                  
                 rs.forEach(r -> {
                  String[] row = new String[7];
                    row[0] = r.getString("id");
                    row[1] = r.getString("name");
                    row[2] = r.getString("longitude");
                    row[3] =  r.getString("latitude");
                    row[4] =  r.getString("pop");
                    row[5] =  r.getString("confirmes");
                    row[6] =  r.getString("morts");
                    model.addRow(row);
                   });
                 JOptionPane.showConfirmDialog(this, "Save with success", "Save with success", JOptionPane.INFORMATION_MESSAGE);
            } //        else if (!id.matches("^[0-9]{8}$")) {
            

                
 
         
         
    }   
    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked
      int i = tblStudents.getSelectedRow();
        TableModel model = tblStudents.getModel();
        txtLid.setValue(model.getValueAt(i, 0));
        txtFname.setText(model.getValueAt(i, 1).toString());
        txtLatitude.setText(model.getValueAt(i, 2).toString());
        txtLongitude.setText(model.getValueAt(i, 3).toString());
        txtPop.setValue(model.getValueAt(i, 4));
        txtConfirmes.setValue(model.getValueAt(i, 5));
        txtMorts.setValue(model.getValueAt(i, 6));        // TODO add your handling code here:
    }//GEN-LAST:event_tblStudentsMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            int i =tblStudents.getSelectedRow();
        DefaultTableModel tblmodel = (DefaultTableModel) tblStudents.getModel();
        if(i>=0)
        {
            tblmodel.setValueAt(txtLid.getValue(), i, 0);
            tblmodel.setValueAt(txtFname.getText(), i, 1);
            tblmodel.setValueAt(txtLongitude.getText(), i, 2);
            tblmodel.setValueAt(txtLatitude.getText(), i, 3);
            tblmodel.setValueAt(txtPop.getValue(), i, 4);
            tblmodel.setValueAt(txtConfirmes.getValue(), i, 5);
            tblmodel.setValueAt(txtMorts.getValue(), i, 6);
            
        }else{
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CovidGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CovidGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CovidGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CovidGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CovidGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPCity;
    private javax.swing.JPanel jPConnection;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpPopulation;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTbCities;
    private javax.swing.JButton jbAdd;
    private javax.swing.JButton jbConnect;
    private javax.swing.JButton jbInitDB;
    private javax.swing.JButton jbRefresh;
    private javax.swing.JTextField jtxtCityID;
    private javax.swing.JTextField jtxtCityName;
    private javax.swing.JTextField jtxtDbName;
    private javax.swing.JTextField jtxtLatitude;
    private javax.swing.JTextField jtxtLongitude;
    private javax.swing.JTextField jtxtNode;
    private javax.swing.JTextField jtxtNode2;
    private javax.swing.JTextField jtxtPort;
    private javax.swing.JTable tblStudents;
    private javax.swing.JSpinner txtConfirmes;
    private javax.swing.JTextPane txtFname;
    private javax.swing.JTextPane txtLatitude;
    private javax.swing.JSpinner txtLid;
    private javax.swing.JTextPane txtLongitude;
    private javax.swing.JSpinner txtMorts;
    private javax.swing.JSpinner txtPop;
    // End of variables declaration//GEN-END:variables

  
}
